project:
  type: website
  output-dir: docs

website:
  favicon: resources/logo-files/fishsize-logo.png
  navbar:
    logo: resources/logo-files/fishsize-logo-wide2.png
    left:
      - text: Home
        href: index.qmd
      - text: Our team
        href: pages/team.qmd
      - text: Research
        href: pages/research.qmd
      - text: Outputs
        href: pages/outputs.qmd
      - text: Big Fish game
        href: pages/bigfishgame.qmd
      - text: Collaborate
        href: pages/join.qmd
  page-footer:
    left: |
      [![](/resources/icons/ic--baseline-mail.svg)](mailto:info@fishsizeproject.org) [info@fishsizeproject.org](mailto:info@fishsizeproject.org)
      <br>
      [![](/resources/icons/mdi--github.svg)](https://github.com/fishsizeproject/) [fishsizeproject](https://github.com/fishsizeproject/) 
      <br><br>
      [Institute of Marine and Antarctic Research](https://www.imas.utas.edu.au/)<br>
      20 Castray Esplanade<br>
      Battery Point TAS 7000<br>
      Australia<br>
    right: |
      <i>We acknowledge the traditional owners of the land on which we live and work.<br>
      Sovereignty was never ceded </i><img src="/resources/images/Australian_Aboriginal_Flag.png" class="img-fluid" style="height: 1em;">
      <br><br><br>
      © FishSize Project, 2024<br>
      Website created by [Tormey Reimer](https://drtreimer.com)
    center: |
      [![](/resources/logo-files/fishsize-logo-wide2.png){fig-alt="FishSize Project" fig-align="center" width="10vw" fig-valign="middle"}](/index.qmd)
    border: false
    background: primary
    foreground: light

format:
  html:
    logo: resources/logo-files/fishsize-logo.png
    theme: [solana, theme/theming.scss]
    css: [theme/styles.css, theme/team-lightbox-class.css]
    toc: false
    anchor-sections: false
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 1450px
      margin-width: 100px
      gutter-width: 1.5em

editor: source
