---
title: "Research"
---

# Our research focuses

## General properties of intra-specific size distributions 

## Temperature impacts on fish sizes  

Temperature has large impacts on fish sizes, both naturally and also through human induced climate change. However, it is still not clear how temperature might affect growth, size structure or mean sizes in natural populations and we use diverse data sources and simulations to explore that. 

1.  Using underwater visual survey data from Reef Life Survey (<https://reeflifesurvey.com/>) we show that mean lengths of fish in natural populations can either increase or decrease with temperature changes across space. This temperature driven change in mean length is very strong (3% change per 1C), which means that average fish length on the warm and cool edge of the fish distribution area can be up to 30% different. Moreover, global warming driven changes in average fish size through time are often qualitatively similar, but rate of change is nearly 10 times faster. But this raises many other questions, which we aim to answer below. 

2.  Is the increase in mean size in warmer waters compatible with the temperature size rule, which states that in warmer conditions fish grow to smaller maturation sizes? 

3.  Fish size distributions are shaped by rates of growth and mortality, and by using simulation modelling we can manipulate these two parameters to see how population mean and maximum size might change under different temperature conditions. Using these methods we can show that it is possible to get increasing population mean sizes, even though the maximum and asymptotic size may be declining, as predicted by the temperature size rule.

## Applying size based models to assess human impacts 

## Using historical records to understand shifting baselines 

Historical data helps us understand the cumulative impact of human activities and minimise the shifting baseline syndrome by estimating the degree to which human activities can alter marine fish populations and ecosystems. We aim to incorporate historical records (oral histories, photographs, newspaper articles, logbooks) for estimating past fish population size distributions at local and regional scales. Examples of the use of historical sources to understand past fisheries dynamics: 

-   Chong-Montenegro C, Thurstan RH, Pandolfi JM (**2022**) Quantifying the historical development of recreational fisheries in Southeast Queensland, Australia. Mar Ecol Prog Ser 696:135-149. <https://doi.org/10.3354/meps14138>
